;;;; Bela

(let ((hands (read))
      (trump (coerce (read) 'character))
      (card nil)
      (total 0))
  (dotimes (i (* 4 hands))
    (setq card (read-line))
    (case (char card 0)
      (#\A (incf total 11))
      (#\K (incf total 4))
      (#\Q (incf total 3))
      (#\T (incf total 10))
      (#\J (if (eq (char card 1) trump)
               (incf total 20)
               (incf total 2)))
      (#\9 (when (eq (char card 1) trump)
                 (incf total 14)))))
  (write total))
